### ISSUE TITLE
ionic-webview

### ISSUE THREAD

**Issue by godhand1607** [dpa99c/cordova-plugin-inappbrowser-popup-bridge#10]
Wanted to confirm if the popup-bridge works if we embed the paypal button on the ionic-webview directly and not using an inappbrowser to open up a page that has the paypal button in it?

**Comment by dpa99c** [comment]
This plugin specifically extends the inappbrowser webview to support PayPal in webpages loaded into the inappbrowser.

ionic-webview applies to the main Cordova app webview - if you wish to add paypal functionality to your Cordova app running in the main webview, you should use one of the various Cordova Paypal plugins.
