### ISSUE TITLE
Google Pay integration?

### ISSUE THREAD

**Issue by SamuelMichelRiad** [dpa99c/cordova-plugin-inappbrowser-popup-bridge#11]
Has anyone been able to use this plugin for Google Pay payments? As far as I understand, Google Pay also requires the ability to open popups to perform the payment.

**Comment by dpa99c** [comment]
This solution is specifically for PayPal and requires the Braintree JS SDK to be present in the web page loaded into the WebView.
It will not work as a generic solution for other payment systems such as Google Pay.

**Comment by SamuelMichelRiad** [comment]
@dpa99c, thanks for your reply. Would you have any general suggestions on how to go about enabling generic popups from IAB?

**Comment by dpa99c** [comment]
AFAIK there's no generic solution - WebViews (as used by Cordova's IAB) do not support popup windows since they are a feature of a full browser. If possible, I'd would open the page in the system browser which _does_ support popup windows.

**Comment by SamuelMichelRiad** [comment]
Thanks again - I've already tried opening the payment page in the system browser (through IAB, using _system as the target), and the payment page does indeed work as expected, however my app either hangs or restarts when I bring it to the foreground again :(
