### ISSUE TITLE
Incompatibility with cordova-plugin-facebook4 on iOS platform

### ISSUE THREAD

**Issue by alexgpeppe** [dpa99c/cordova-plugin-inappbrowser-popup-bridge#7]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

On iOS devices the attempt to login with facebook with Facebook app always fails with the response error `User cancelled.`.
The bug has been tested on a clean Ionic app containing a minimal plugins set, it appeared after installing this plugin.

**Expected behavior:**

On iOS devices the attempt to login with facebook with Facebook app correctly succeeds as the login through email or phone number does.

**Steps to reproduce:**

On iOS click the button to login with facebook and from the webview shown below choose to login with the Facebook app.
This bug appears only on iOS, on android everything works as expected.

<img src="https://user-images.githubusercontent.com/22143453/48131333-feedd400-e28f-11e8-9e19-81e2e091b4e4.jpg" width="200"/>

**Environment information**

- Cordova CLI version 
	- 7.1.0
- Cordova platform version
	- ios 4.5.5
- Plugins & versions installed in project (including this plugin)
    - cordova-plugin-device 2.0.2 "Device"
    - cordova-plugin-facebook4 3.1.0 "Facebook Connect"
    - cordova-plugin-inappbrowser-popup-bridge 1.0.17 "InAppBrowser with PopupBridge"
    - cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
    - cordova-plugin-splashscreen 5.0.2 "Splashscreen"
    - cordova-plugin-statusbar 2.4.2 "StatusBar"
    - cordova-plugin-whitelist 1.3.3 "Whitelist"
    - cordova-plugin-wkwebview-engine 1.1.4 "Cordova WKWebView Engine"

- Dev machine OS and version, e.g.
    - OSX
        - ProductName:    Mac OS X
        - ProductVersion: 10.13.6
        - BuildVersion:   17G65

_Runtime issue_
- Device details
    - iPhone X
- OS details
    - iOS 11.4.1 (15G77)	
	
_iOS build issue:_
- Node JS version
    - v6.5.0
- XCode version
    - Version 10.0 (10A255)

- Ionic environment info
    - ionic (Ionic CLI)  : 4.3.1
    - Ionic Framework    : ionic-angular 3.9.2
    - @ionic/app-scripts : 3.2.0

- Installed Ionic Native modules and versions
    - @ionic-native/core@4.15.0
    - @ionic-native/facebook@4.17.0
    - @ionic-native/splash-screen@4.15.0
    - @ionic-native/status-bar@4.15.0

**Comment by alexgpeppe** [comment]
Any updates about this issue...?

**Comment by dpa99c** [comment]
The iOS part of this plugin is based on the WKWebView component of [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) with an extension to support Braintree's PopupBridge. 

Can you reproduce the same issue with the current master version (`3.1.0-dev`) of `cordova-plugin-inappbrowser` using the WKWebView implementation (`usewkwebview=yes`) ?

**Comment by alexgpeppe** [comment]
Thanks for your fast reply, @dpa99c. I couldn't find the version you mentioned, but I replaced the `cordova-plugin-inappbrowser-popup-bridge` with the version `3.0.0` of `cordova-plugin-inappbrowser` and now facebook login works as expected. I also managed to add a payment method using braintree without changing my code (I didn't have to use `usewkwebview=yes`), so now everything is fine for me.
