### ISSUE TITLE
Need MSAL Cordova plugin for the Cordova Version 6.5.0

### ISSUE THREAD

**Issue by judefelixantony** [dpa99c/cordova-plugin-inappbrowser-popup-bridge#9]
Please since our mobile application Cordova version is 6.5.0. We are looking for the compatibility version of MSAL which will work with  Cordova version 6.5.0.

Kindly help me in this.

**Comment by dpa99c** [comment]
minimum supported versions by this plugin are `cordova@10` CLI and `cordova-android@9` and `cordova-ios@6.1.0`.
please see the [example project](https://github.com/dpa99c/cordova-plugin-inappbrowser-popup-bridge-test) for demonstration of usage.
